name: lint

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout data
        uses: actions/checkout@v3
      - name: Install ESLint
        run: |
          npm install eslint@8.22.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        id: script
        run: npx eslint "projects/web/**/*.{ts,html}"
          --format @microsoft/eslint-formatter-sarif
          --output-file lint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: lint-results.sarif
          wait-for-processing: true
      - name: Get result
        if: ${{ steps.script.outcome != 'success' }}
        run: exit 1
